
DROP TABLE IF EXISTS STUDENT_COMPETITIONS
DROP TABLE IF EXISTS STUDENTS
DROP TABLE IF EXISTS FUTURE_SCHOOLS
DROP TABLE IF EXISTS CLASSES
DROP TABLE IF EXISTS COMPETITIONS

CREATE TABLE FUTURE_SCHOOLS
(
	FUTURE_SCHOOL_ID INT PRIMARY KEY,
	FUTURE_SCHOOL_NAME VARCHAR(128) NOT NULL,
	FUTURE_SCHOOL_GEO_LATITUDE DECIMAL,
	FUTURE_SCHOOL_GEO_LONGTITUDE DECIMAL
)

CREATE TABLE CLASSES
(
	CLASS_ID INT PRIMARY KEY,
	CLASS_LETTER VARCHAR(128) NOT NULL,
	CLASS_NAME VARCHAR(128) NOT NULL,
	CLASS_YEAR INT NOT NULL,
	CLASS_DESCRIPTION VARCHAR(1024),
)

CREATE TABLE COMPETITIONS
(
	COMPETITION_ID INT PRIMARY KEY,
	COMPETITION_NAME VARCHAR(128) NOT NULL
)

CREATE TABLE STUDENTS
(
	STUDENT_ID INT PRIMARY KEY,
	STUDENT_FIRST_NAME VARCHAR(32) NOT NULL,
	STUDENT_LAST_NAME VARCHAR(32) NOT NULL,
	STUDENT_GENDER CHAR(1) NOT NULL,
	STUDENT_GEO_LATITUDE DECIMAL,
	STUDENT_GEO_LONGITUDE DECIMAL,
	STUDENT_TRAVEL_TIME_MINUTES INT,
	STUDENT_TRAVEL_DISTANCE_KM DECIMAL,
	STUDENT_FUTURE_SCHOOL_ID INT FOREIGN KEY REFERENCES FUTURE_SCHOOLS(FUTURE_SCHOOL_ID),
	STUDENT_CLASS_ID INT FOREIGN KEY REFERENCES CLASSES(CLASS_ID)
)

CREATE TABLE STUDENT_COMPETITIONS
(
	STUDENT_ID INT FOREIGN KEY REFERENCES STUDENTS(STUDENT_ID),
	COMPETITION_ID INT FOREIGN KEY REFERENCES COMPETITIONS(COMPETITION_ID),
	STUDENT_COMPETITION_YEAR INT NOT NULL,
	PRIMARY KEY (STUDENT_ID, COMPETITION_ID)
)